# Generated by Django 5.2 on 2025-05-28 03:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='新對話', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('embedding_model', models.CharField(default='BAAI/bge-large-zh', max_length=255)),
                ('llm_model', models.CharField(default='gpt-3.5-turbo', max_length=255)),
                ('temperature', models.FloatField(default=0.1)),
                ('max_tokens', models.IntegerField(default=1000)),
                ('chunk_size', models.IntegerField(default=1000)),
                ('chunk_overlap', models.IntegerField(default=200)),
                ('top_k', models.IntegerField(default=4)),
                ('use_rag_fusion', models.BooleanField(default=False)),
                ('use_reranking', models.BooleanField(default=False)),
                ('use_cot', models.BooleanField(default=False)),
                ('use_bm25', models.BooleanField(default=True)),
                ('use_contextual_embeddings', models.BooleanField(default=True)),
                ('use_hybrid', models.BooleanField(default=True)),
                ('use_intelligent_splitting', models.BooleanField(default=True)),
                ('openai_api_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='secondary', max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_message', models.TextField()),
                ('assistant_message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('related_docs', models.JSONField(blank=True, null=True)),
                ('show_sources', models.BooleanField(default=True)),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(max_length=1024, upload_to='uploads/')),
                ('file_type', models.CharField(max_length=10)),
                ('file_size', models.BigIntegerField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('processed', 'Processed'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='uploading', max_length=20)),
                ('chunks_count', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(blank=True, to='api.tag')),
            ],
        ),
    ]
